routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/clear', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
});

Route::get('/', function () {
    return view('front/index');
});

Route::get('/mobilya/gardiroplar', function()
{
	return view('front/mobilya/gardiroplar');
});

Route::get('/mobilya/gardiroplar/surgulu-gardiroplar', function()
{
	return view('front/mobilya/surgulu_gardiroplar');
});
Route::get('/gardiroplar/surgulu-gardiroplar/surgulu-gardiroplar-urun1', function()
{
	return view('front/mobilya/surgulu_gardiroplar_urun1');
});

Route::get('/mobilya/gardiroplar/kapakli-gardiroplar', function()
{
	return view('front/mobilya/kapakli_gardiroplar');
});

Route::get('/gardiroplar/kapakli-gardiroplar/kapakli-gardiroplar-urun1', function()
{
	return view('front/mobilya/kapakli_gardiroplar_urun1');
});


Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::group(['prefix' => 'panel', 'middleware' => ['auth','admin']], function () {
    
     Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');

     Route::resource('category','Admin\CategoriesController');
     Route::resource('product','Admin\ProductsController');
     Route::get('product/image/{productId}','Admin\ProductsController@image');
     Route::get('product/image/deleteImage/{productId}','Admin\ProductsController@DeleteImage');
     Route::post('product/image-upload/{productId}','Admin\ProductsController@uploadImages');

    });

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable=['name','slug'];
    protected $table='product_categories';

    public function products()
    {
//        return $this->hasMany('App\Product');
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;
use Validator;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $categories=Category::all();

        return view('admin.category.index')->with('categories', $categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   

        $validator = Validator::make($request->all(), [
        'name' => 'required',
        
        ]);

        if ($validator->fails()) {
            return redirect('panel/category/create')
                        ->withErrors($validator)
                        ->withInput(); }
        try {
             $data = array(
                     "name" => $request->name,
                     
                   );

            //$categories=Category::create($data);
            Category::create(['name'=>$request->name,'slug'=>str_slug($request->name)]);
           
            return redirect()->route('category.index');
            
        }  catch(\Exception $e){
            return "Girmiş Olduğunuz Kategori Zaten Kayıtlı...";
           }

        //return redirect()->route('category.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category=Category::find($id);
        return view('admin.category.edit',compact(['category']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category=Category::find($id);
        $formInput=$request->except('image');

//        validation
        $this->validate($request,[
            'name'=>'required'
        ]);

       

         $category->update($formInput);
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        Category::destroy($id);
        return back();
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.layout.admin')

@section('content')

	<h3>Ürün Ekle</h3>
      @if(Session::has('message'))
            <div class="alert alert-info">
                <p>{{ Session::get('message') }}</p>
            </div>
        @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif



    {!! Form::open(['route' => 'category.store', 'method' => 'post' , 'id'=>'category' , 'class' => 'form-horizontal form-label-left' , 'data-parsley-validate'=>'']) !!}
    {{ Form::label('name','Kategori Adı',['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])}}
 <div class="col-md-6 col-sm-6 col-xs-12">
    {{ Form::text('name','', ['class' => 'form-control col-md-7 col-xs-12'])}}
 </div>

    {{ Form::submit('Kaydet',['class' => 'btn btn-success']) }}
                        
    {!! Form::close() !!}
              

@endsection

@section('js')
<script src="{{ URL::to('') }}/admin/js/categories.js"></script>
@endsection
    
    
    

resources/views/admin/category/edit.blade.php
@extends('admin.layout.admin')

@section('content')

    <h3>Kategoriyi Düzenle</h3>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {!! Form::model($category,['route' => ['category.update',$category->id], 'method' => 'PUT', 'files' => true]) !!}
            <div class="form-group">
                {{ Form::label('name', 'Kategori Adı') }}
                {{ Form::text('name', null, array('class' => 'form-control','required'=>'','minlength'=>'5')) }}
            </div>

   

             {{ Form::submit('Düzenle', array('class' => 'btn btn-success')) }}
            {!! Form::close() !!}


        </div>
    </div>



@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layout.admin')

@section('content')

    <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Kategori  <small>Listeleme</small></h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Tüm Kategoriler</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <p>Simple table with project listing with progress and editing options</p>

                    <!-- start project list -->
                    <table class="table table-striped  table-hover">
                      <thead>
                        <tr>
                          <th style="width: 1%">#</th>
                          <th style="width: 20%">Kategori Adı</th>
                          <th>Durumu</th>
                          <th style="width: 20%">#Edit</th>
                        </tr>
                      </thead>
                      <tbody>

                        @forelse($categories as $category)
                        <tr>
                          <td>#</td>
                          <td>
                            <a>{{$category->name}}</a>
                            <br />
                            <small>{{$category->created_at}}</small>
                          </td>
                     
                          <td>
                            <input class = "toggle_check"
                                           data-onstyle="success"
                                           data-size = "mini"
                                           data-on="Aktif"
                                           data-off="Pasif"
                                           data-offstyle="danger"
                                           type="checkbox"
                                           data-toggle="toggle"
                                           dataID="<?php echo $category->id; ?>"
                                     <?php echo ($category->isActive == 1) ? "checked" : ""; ?>   
                                    />
                          </td>
                          <td>
                            <a href="{{route('category.edit',$category->id)}}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Düzenle </a>
                            <form action="{{route('category.destroy',$category->id)}}" method="POST" style="float:right; padding-right: 35%">
                             {{csrf_field()}}
                             {{method_field('DELETE')}}
                             <button class="btn btn-xs btn-danger" id="CategoryDelete" dataURL="{{route('category.destroy',$category->id)}}"  type="button"   ><i class="fa fa-trash-o"></i>Sili</button>
                            <!--  <button data-toggle="tooltip"   data-placement="top" title="Sil"  dataURL="{{route('category.destroy',$category->id)}}" id="CategoryDelete"  class="btn btn-xs btn-danger" type="button" onclick="return confirm('{{$category->name}} Adlı Ürün Silinecek. Silmek istediğinizden emin misin')" ><i class="fa fa-trash-o"></i>Sil</button>

                            <a href="{{route('category.destroy',$category->id)}}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Sil </a>
                           <input class="btn btn-danger btn-xs" type="submit"><i class="fa fa-trash-o"></i>-->
                                <!-- <a data-toggle="tooltip"   data-placement="top" title="Sil" class=" modal-basic btn btn-xl btn-danger"
                       href="{{route('category.destroy',$category->id)}}" onclick="return confirm('{{$category->name}} Adlı Ürün Silinecek. Silmek istediğinizden emin misin')"><i class="fa fa-trash"></i></a>-->
                
                
                           </form>

                           <a data-toggle="tooltip"   data-placement="top" title="Sil" class=" modal-basic btn btn-xl btn-danger"
                       href="{{route('category.destroy',$category->id)}}" onclick="return confirm('{{$category->name}} Adlı Ürün Silinecek. Silmek istediğinizden emin misin')"><i class="fa fa-trash"></i></a>
                          </td>
                        </tr>
                         @empty

                        <h3>Listede Kategori Bulunamadı</h3>
                      
                        @endforelse
                      </tbody>
                    </table>
                    <!-- end project list -->
                  
                </div>
              </div>
            </div>
          </div>     
       

@endsection

@section('js')

  <script>
    function confirmDelete() {
      var dataURL = $(this).attr("dataURL");
    swal({
        title: "Are you sure?",
        text: "You will not be able to recover this imaginary file!",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes, delete it!",
        closeOnConfirm: false
    }, function (isConfirm) {
        if (!isConfirm) return;
        $.ajax({
             headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: dataURL,
            type: "DELETE",
            data: {
                id: 5
            },
            dataType: "html",
            success: function () {
                swal("Done!", "It was succesfully deleted!", "success");
            },
            error: function (xhr, ajaxOptions, thrownError) {
                swal("Error deleting!", "Please try again", "error");
            }
        });
    });
}

$(document).ready(function(){
    $("#CategoryDelete").click(function(){
      var dataURL = $(this).attr("dataURL");
     swal({
      title: "Silmek İstediğinizden Emin Misiniz?",
      text: "Bu Ürün Tamamen Silinecek!",
      type: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "Evet , Sil Şunu!",
      closeOnConfirm: false
    },
    function(isConfirm){
      
           if (!isConfirm) return;
        $.ajax({

            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: dataURL,
            type: "DELETE",
           
            dataType: "html",
            success: function () {
                swal("Done!", "It was succesfully deleted!", "success");
                location.reload();
            },
            error: function (xhr, ajaxOptions, thrownError) {
                swal("Error deleting!", "Please try again", "error");
            }
        });



    });
        });
      
      });




</script>

@endsection

<link rel="stylesheet" type="text/css" href="/admin/css/bootstrap-toggle.min.css">
@section('css')
    
    
    