routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/clear', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
});

Route::get('/', function () {
    return view('front/index');
});

Route::get('/mobilya/gardiroplar', function()
{
	return view('front/mobilya/gardiroplar');
});

Route::get('/mobilya/gardiroplar/surgulu-gardiroplar', function()
{
	return view('front/mobilya/surgulu_gardiroplar');
});
Route::get('/gardiroplar/surgulu-gardiroplar/surgulu-gardiroplar-urun1', function()
{
	return view('front/mobilya/surgulu_gardiroplar_urun1');
});

Route::get('/mobilya/gardiroplar/kapakli-gardiroplar', function()
{
	return view('front/mobilya/kapakli_gardiroplar');
});

Route::get('/gardiroplar/kapakli-gardiroplar/kapakli-gardiroplar-urun1', function()
{
	return view('front/mobilya/kapakli_gardiroplar_urun1');
});


Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::group(['prefix' => 'panel', 'middleware' => ['auth','admin']], function () {
    
     Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');

     Route::resource('category','Admin\CategoriesController');
     Route::resource('product','Admin\ProductsController');
     Route::get('product/image/{productId}','Admin\ProductsController@image');
     Route::get('product/image/deleteImage/{productId}','Admin\ProductsController@DeleteImage');
     Route::post('product/image-upload/{productId}','Admin\ProductsController@uploadImages');

    });

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{   
    protected $table='products';

    protected $fillable=['name','description','size','category_id','image','price'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function images()
    {
    	return $this->hasMany(ProductImage::class);
    }

    public function reviews()
    {
        return $this->hasMany(ProductReview::class);
    }

    public function getStarRating()
    {
        $count = $this->reviews()->count();
        if(empty($count)){
            return 0;
        }
        $starCountSum=$this->reviews()->sum('rating');
        $average=$starCountSum/ $count;

       return $average;

    }

}

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Http\Request;
use Validator;


class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products=Product::all();
        return view('admin.product.index')->with('products',$products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $categories=Category::pluck('name','id');
        return view('admin.product.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formInput=$request->except('image');

//        validation
        $this->validate($request,[
            'name'=>'required',
            'price'=>'required',
            'description'=>'required',
            'image'=>'image|mimes:png,jpg,jpeg|max:10000'
        ]);
//        image upload
        $image=$request->image;
        if($image){
            $imageName=$image->getClientOriginalName();
            $image->move('images',$imageName);
            $formInput['image']=$imageName;
        }
        
        Product::create($formInput);
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product=Product::find($id);
        $categories=Category::pluck('name','id');
        return view('admin.product.edit',compact(['product','categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product=Product::find($id);
        $formInput=$request->except('image');

//        validation
        $this->validate($request,[
            'name'=>'required',
            'price'=>'required',
            'image'=>'image|mimes:png,jpg,jpeg|max:10000'
        ]);

        //        image upload
        $image=$request->image;
        if($image){
            $imageName=$image->getClientOriginalName();
            $image->move('images',$imageName);
            $formInput['image']=$imageName;
        }

         $product->update($formInput);
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);
       /*if ($delete) {
           return response(['durum'=>'success','baslik'=>'Başarılı','icerik'=>'Kayıt Başarılı...']);
       }
       else{
        return response(['durum'=>'error','baslik'=>'Hatalı','icerik'=>'Kayıt Başarısız...']);
       }*/
        //return back();
    }

     public function image($id)
    {
        $products=Product::where('id',$id)->get();
        return view('admin.product.image')->with('products',$products);
        
        
    }

    public function deleteImage($id)
    {
        ProductImage::destroy($id);
        return back();
    }

    public function uploadImages($productId,Request $request)
    {

            
        $product=Product::find($productId);

        //        image upload
        $image=$request->file('file');

        if($image){
            $imageName=time(). $image->getClientOriginalName();
            $image->move('images',$imageName);
            $imagePath= "/images/$imageName";
            $product->images()->create(['image_path'=>$imagePath]);
        }

        return "done";
        // Product::create($formInput);
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layout.admin')

@section('content')

    <h3>Ürün Ekle</h3>
      @if(Session::has('message'))
            <div class="alert alert-info">
                <p>{{ Session::get('message') }}</p>
            </div>
        @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {!! Form::open(['route' => 'product.store', 'method' => 'POST', 'files' => true, 'data-parsley-validate'=>'']) !!}

            <div class="form-group">
                {{ Form::label('name', 'Ürün Adı') }}
                {{ Form::text('name', null, array('class' => 'form-control','required'=>'','minlength'=>'5')) }}
            </div>

            <div class="form-group">
                {{ Form::label('description', 'Ürün Açıklaması') }}
                {{ Form::text('description', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                {{ Form::label('price', 'Ürün Fiyatı') }}
                {{ Form::text('price', null, array('class' => 'form-control')) }}
            </div>

           

            <div class="form-group">
                {{ Form::label('category_id', 'Kategoriler') }}
                {{ Form::select('category_id', $categories, null, ['class' => 'form-control','placeholder'=>'Kategori Seçiniz']) }}
            </div>

            <!--<div class="form-group">
                {{ Form::label('image', 'Ürün Resimi') }}
                {{ Form::file('image',array('class' => 'form-control')) }}
            </div>-->

             {{ Form::submit('Ekle', array('class' => 'btn btn-success')) }}
            {!! Form::close() !!}

        </div>
    </div>



@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layout.admin')

@section('content')

    <h3>Ürünü Düzenle</h3>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {!! Form::model($product,['route' => ['product.update',$product->id], 'method' => 'PUT', 'files' => true]) !!}
            <div class="form-group">
                {{ Form::label('name', 'Ürün Adı') }}
                {{ Form::text('name', null, array('class' => 'form-control','required'=>'','minlength'=>'5')) }}
            </div>

            <div class="form-group">
                {{ Form::label('description', 'Açıklama') }}
                {{ Form::text('description', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                {{ Form::label('price', 'Fiyatı') }}
                {{ Form::text('price', null, array('class' => 'form-control')) }}
            </div>

           
            <div class="form-group">
                {{ Form::label('category_id', 'Kategori') }}
                {{ Form::select('category_id', $categories, null, ['class' => 'form-control','placeholder'=>'Select Category']) }}
            </div>

            <div class="form-group">
                {{ Form::label('image', 'Image') }}
                {{ Form::file('image',array('class' => 'form-control')) }}
            </div>

             {{ Form::submit('Düzenle', array('class' => 'btn btn-default')) }}
            {!! Form::close() !!}


        </div>
    </div>



@endsection

resources/views/admin/product/image.blade.php
@extends('admin.layout.admin')

@section('content')

	<h3>Resim Ekle</h3>
   
      <div class="row">       
            @foreach($products as $product)
            <div class="col-md-12" style="width: 100%; padding-bottom: 20px">
            
            <form action="/panel/product/image-upload/{{$product->id}}" method="POST" class="dropzone" id="my-awesome-dropzone-{{$product->id}}">
              {{csrf_field()}}

             </form>

            </div>


              
             
        @endforeach

          

        <div class="col-md-12">

            <div class="box" style="height: 800px; width:100%">
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <thead>
                            <th>Önizleme</th>
                            <th>isActive</th>
                            <th>isCover</th>
                            <th class="col-md-2">İşlemler</th>
                        </thead>
                        <tbody class="sortableList" postUrl="room/roomImageRankUpdate">
                     @foreach($product->images as $image) 
                            <tr id="">
                                <td>
                                    <a class="thumbnail fancybox" rel="ligthbox" href="{{$image->image_path}}">
                                        <img
                                            width="80"
                                            src="{{$image->image_path}}"
                                            alt=""
                                            class="img-responsive"
                                        />
                                    </a>

                                </td>
                                <td>
                                    <input class = "toggle_check"
                                           data-onstyle="success"
                                           data-size = "mini"
                                           data-on="Aktif"
                                           data-off="Pasif"
                                           data-offstyle="danger"
                                           type="checkbox"
                                           data-toggle="toggle"
                                           dataID="<?php echo $image->id; ?>"
                                     <?php echo ($image->isActive == 1) ? "checked" : ""; ?>   
                                    />
                                </td>
                                <td>
                                    <input class = "toggle_check"
                                           data-onstyle="success"
                                           data-size = "mini"
                                           data-on="Aktif"
                                           data-off="Pasif"
                                           data-offstyle="danger"
                                           type="checkbox"
                                           data-toggle="toggle"
                                           dataID="<?php echo $image->id; ?>"
                                     <?php echo ($image->isCover == 1) ? "checked" : ""; ?>   
                                    />
                                </td>
                                <td>
                                    <a href="deleteImage/{{$image->id}}">
                                        <i class="fa fa-trash" style="font-size:16px;"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
                <!-- /.box-body -->
         
        </div>
    </div>
    
    <button id="deneme" type="button">tıkla</button>
              

@endsection

@section('js')
    <script src="/admin/js/jquery.fancybox.min.js" type="text/javascript"></script>
    <script src="/admin/js/bootbox.min.js" type="text/javascript" ></script>
    <script src="/admin/js/bootstrap-toggle.min.js" type="text/javascript" ></script>

<script>
       $(document).ready(function(){
        $('.deneme').click(function(){
            alert('fff');
        })
        //FANCYBOX
        //https://github.com/fancyapps/fancyBox
        $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });
    });
    
          // Bootstrap Toggle init
        $('.toggle_check').bootstrapToggle();

        // isActive Change

        $('.toggle_check').change(function () {

            alert('fgfd');

        });


    });
</script>

@endsection

@section('css')

<link rel="stylesheet" type="text/css" href="/admin/css/jquery.fancybox.min.css">
<link rel="stylesheet" type="text/css" href="/admin/css/bootstrap-toggle.min.css">
<style type="text/css">
       .dropzone{
        border: 2px dashed #d4d4d4;
        height: auto;
        background-color: #fff;
        color: black;
        font-size: 20px;
        font-style: italic;
    }

    .gallery
    {
        display: inline-block;
        margin-top: 20px;
    }

    .thumbnail {
        width: 90px;
        height:90px;
    }
</style>

@endsection
    
    
    

resources/views/admin/product/index.blade.php
@extends('admin.layout.admin')

@section('content')

       <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Ürün  <small>Listeleme</small></h3>
                   @if(Session::has('message'))
            <div class="alert alert-info">
                <p>{{ Session::get('message') }}</p>
            </div>
        @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Tüm Ürünler</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <p>Simple table with project listing with progress and editing options</p>

                    <!-- start project list -->
                    <table class="table table-striped  hover">
                      <thead>
                        <tr>
                          <th style="width: 1%">#</th>
                          <th style="width: 20%">Ürün Adı</th>
                          <th> Foto</th>
                          <th>Ürün Özellikleri</th>
                          <th>Ürün Fiyatı</th>
                          <th>Durumu</th>
                          <th style="width: 20%">#İşlemler</th>
                        </tr>
                      </thead>
                      <tbody>

                        @forelse($products as $product)
                        <tr>
                          <td>#</td>
                          <td>
                            <a>{{$product->name}}</a>
                            <br />
                            <small>Created 01.01.2015</small>
                          </td>
                          <td>
                            <ul class="list-inline">
                            @foreach ($product->images as $image)
                              <li>
                                <img src="{{$image->image_path}}" style="max-width: 100px">
                              </li>
                            @endforeach
                            </ul>
                          </td>
                          <td>
                              {{$product->description}}                     
                          </td>
                          <td>
                            {{$product->price}}  
                          </td>
                          <td>
                            <div class="">
                            <label>
                              <input type="checkbox" class="js-switch" checked /> Aktif
                            </label>
                          </div>
                          </td>
                          <td>
                            <a href="{{route('product.edit',$product->id)}}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> </a>
                            <a href="product/image/{{$product->id}}" class="btn btn-info btn-xs"><i class="fa fa-image"></i> </a>
                                                        
                             <button class="btn btn-xs btn-danger" id="ProductDelete" dataURL="{{route('product.destroy',$product->id)}}"  type="button"   ><i class="fa fa-trash-o"></i>Sil</button>
                            <button href="#" dataURL="{{route('product.destroy',$product->id)}}" onclick="confirmDelete()" >Delete record #23</button>
                            <a href="{{route('product.destroy',$product->id)}}" onclick="return confirm('Are you sure you want to delete this item?');">DeleteConirm</a>
                          </td>
                        </tr>
                         @empty

                        <h3>Listede Ürün Bulunamadı</h3>
                      
                        @endforelse
                      </tbody>
                    </table>
                    <!-- end project list -->

                  </div>
                </div>
              </div>
            </div>
          </div>  
          <a href="#" onclick="confirmDelete()">Ajax in this Delete will NOT work</a>
@endsection

@section('js')



<script>
    function confirmDelete() {
      var dataURL = $(this).attr("data-href");
    swal({
        title: "Are you sure?",
        text: "You will not be able to recover this imaginary file!",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes, delete it!",
        closeOnConfirm: false
    }, function (isConfirm) {
        if (!isConfirm) return;
        $.ajax({
             headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: dataURL,
            type: "DELETE",
            data: {
                id: 5
            },
            dataType: "html",
            success: function () {
                swal("Done!", "It was succesfully deleted!", "success");
            },
            error: function (xhr, ajaxOptions, thrownError) {
                swal("Error deleting!", "Please try again", "error");
            }
        });
    });
}

$(document).ready(function(){
    $("#ProductDelete").click(function(){
      var dataURL = $(this).attr("dataURL");
     swal({
      title: "Silmek İstediğinizden Emin Misiniz?",
      text: "Bu Ürün Tamamen Silinecek!",
      type: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "Evet , Sil Şunu!",
      closeOnConfirm: false
    },
    function(isConfirm){
      
           if (!isConfirm) return;
        $.ajax({

            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: dataURL,
            type: "DELETE",
           
            dataType: "html",
            success: function () {
                swal("Done!", "It was succesfully deleted!", "success");
                location.reload();
            },
            error: function (xhr, ajaxOptions, thrownError) {
                swal("Error deleting!", "Please try again", "error");
            }
        });



    });
        });
      
      });

</script>

@endsection

@section('css')

@endsection